name: Code Quality

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: yarn install --frozen-lockfile

      - name: Checar Prettier
        run: yarn format:check

  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: yarn install --frozen-lockfile

      - name: Rodar ESLint
        run: yarn lint
